import XCTest
@testable import CopyCore

final class RulesEngineTests: XCTestCase {
    func testAllowsNormalContent() {
        let rules = RulesEngine()
        XCTAssertTrue(rules.shouldCapture(types: ["public.utf8-plain-text"], sourceBundleID: "com.apple.Safari"))
    }

    func testSkipsConcealedTransientAndAutoGenerated() {
        let rules = RulesEngine()
        for type in ["org.nspasteboard.ConcealedType",
                     "org.nspasteboard.TransientType",
                     "org.nspasteboard.AutoGeneratedType"] {
            XCTAssertFalse(rules.shouldCapture(
                types: ["public.utf8-plain-text", type], sourceBundleID: "com.apple.Safari"),
                "should skip \(type)")
        }
    }

    func testSkipsOwnPastes() {
        let rules = RulesEngine()
        XCTAssertFalse(rules.shouldCapture(
            types: ["public.utf8-plain-text", CopyPasteboard.selfMarkerType],
            sourceBundleID: nil))
    }

    func testSkipsExcludedApps() {
        let rules = RulesEngine(excludedBundleIDs: ["com.1password.1password"])
        XCTAssertFalse(rules.shouldCapture(
            types: ["public.utf8-plain-text"], sourceBundleID: "com.1password.1password"))
        XCTAssertTrue(rules.shouldCapture(
            types: ["public.utf8-plain-text"], sourceBundleID: "com.apple.Safari"))
    }

    func testNilSourceAllowed() {
        let rules = RulesEngine(excludedBundleIDs: ["com.x.y"])
        XCTAssertTrue(rules.shouldCapture(types: ["public.utf8-plain-text"], sourceBundleID: nil))
    }
}
