import Foundation

public struct RulesEngine: Sendable {
    /// Pasteboard types that must never be captured (nspasteboard.org conventions + own pastes).
    public static let skipTypes: Set<String> = [
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType",
        CopyPasteboard.selfMarkerType,
    ]

    public var excludedBundleIDs: Set<String>

    public init(excludedBundleIDs: Set<String> = []) {
        self.excludedBundleIDs = excludedBundleIDs
    }

    public func shouldCapture(types: [String], sourceBundleID: String?) -> Bool {
        if types.contains(where: Self.skipTypes.contains) { return false }
        if let bundleID = sourceBundleID, excludedBundleIDs.contains(bundleID) { return false }
        return true
    }
}
